version: '3'

includes:
  gradleRoot:
    taskfile: gradle.Taskfile.yml
    dir: .

  github:
    taskfile: github.Taskfile.yml
    dir: .

  frontend:
    taskfile: frontend/Taskfile.yml
    dir: frontend

  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  worker:
    taskfile: worker/Taskfile.yml
    dir: worker

tasks:
  fixAll:
    desc: Apply all automatic fixes
    deps:
      - github:fixLint
      - gradleRoot:fixFormatting
      - frontend:fixFormatting
      - frontend:fixLint
      - infra:fixFormatting
      - infra:fixLint
      - worker:fixFormatting
      - worker:fixLint
